version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: barter-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - barter-net

  api:
    build:
      context: ./barter-api
      dockerfile: Dockerfile
    container_name: barter-api
    depends_on:
      - postgres
      - ollama
    env_file:
      - .env
    ports:
      - "4000:4000"
    networks:
      - barter-net

  frontend:
    build:
      context: ./barter-web
      dockerfile: Dockerfile
    container_name: barter-frontend
    depends_on:
      - api
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - barter-net

  ollama:
    image: ollama/ollama
    container_name: barter-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - barter-net
    restart: unless-stopped

volumes:
  pgdata:
  ollama_data:

networks:
  barter-net:

